
name: Git Jira issue transition

on:
  push

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: GIT
        issuetype: Task
        summary: |
          Build completed for ${{ github.repository }}
          
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
      
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      
      with:
        issue: ${{ steps.create.outputs.issue }}
        transition: "In progress"
