name: Github to Jira integration

on:
  pull_request:
    branches: 
      - main
   
    types: [opened, reopened]

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
        
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ github.head_ref }}
        transition: "In progress"
        
